alter table public.reporting_drive_integrations add column if not exists reserved_organization_drive_folder_id text;
alter table public.event_drive_locations add column if not exists reserved_event_drive_folder_id text;
alter table public.event_drive_locations add column if not exists reserved_final_reports_folder_id text;
alter table public.reporting_drive_integrations add constraint reporting_drive_integrations_reserved_root_nonempty check (reserved_organization_drive_folder_id is null or length(trim(reserved_organization_drive_folder_id))>0);
alter table public.event_drive_locations add constraint event_drive_locations_reserved_event_nonempty check (reserved_event_drive_folder_id is null or length(trim(reserved_event_drive_folder_id))>0);
alter table public.event_drive_locations add constraint event_drive_locations_reserved_reports_nonempty check (reserved_final_reports_folder_id is null or length(trim(reserved_final_reports_folder_id))>0);

create or replace function public.reserve_drive_organization_folder_id(p_integration_id uuid,p_candidate_file_id text) returns text language plpgsql security definer set search_path=public,pg_temp as $$ declare i public.reporting_drive_integrations%rowtype; begin select * into i from public.reporting_drive_integrations where id=p_integration_id for update; if not found or i.deleted_at is not null or not i.enabled or i.status<>'connected' then raise exception 'drive_integration_invalid'; end if; if i.organization_drive_folder_id is not null then return i.organization_drive_folder_id; end if; if i.reserved_organization_drive_folder_id is not null then return i.reserved_organization_drive_folder_id; end if; if nullif(trim(p_candidate_file_id),'') is null then raise exception 'drive_reservation_invalid'; end if; update public.reporting_drive_integrations set reserved_organization_drive_folder_id=trim(p_candidate_file_id) where id=i.id; return trim(p_candidate_file_id); end; $$;
create or replace function public.reserve_drive_event_folder_id(p_location_id uuid,p_candidate_file_id text,p_revision bigint) returns text language plpgsql security definer set search_path=public,pg_temp as $$ declare l public.event_drive_locations%rowtype; begin select * into l from public.event_drive_locations where id=p_location_id for update; if not found or l.deleted_at is not null or l.status='disabled' or l.revision<>p_revision then raise exception 'drive_location_invalid'; end if; if l.event_drive_folder_id is not null then return l.event_drive_folder_id; end if; if l.reserved_event_drive_folder_id is not null then return l.reserved_event_drive_folder_id; end if; if nullif(trim(p_candidate_file_id),'') is null then raise exception 'drive_reservation_invalid'; end if; update public.event_drive_locations set reserved_event_drive_folder_id=trim(p_candidate_file_id) where id=l.id; return trim(p_candidate_file_id); end; $$;
create or replace function public.reserve_drive_reports_folder_id(p_location_id uuid,p_candidate_file_id text,p_revision bigint) returns text language plpgsql security definer set search_path=public,pg_temp as $$ declare l public.event_drive_locations%rowtype; begin select * into l from public.event_drive_locations where id=p_location_id for update; if not found or l.deleted_at is not null or l.status='disabled' or l.revision<>p_revision then raise exception 'drive_location_invalid'; end if; if l.final_reports_folder_id is not null then return l.final_reports_folder_id; end if; if l.reserved_final_reports_folder_id is not null then return l.reserved_final_reports_folder_id; end if; if nullif(trim(p_candidate_file_id),'') is null then raise exception 'drive_reservation_invalid'; end if; update public.event_drive_locations set reserved_final_reports_folder_id=trim(p_candidate_file_id) where id=l.id; return trim(p_candidate_file_id); end; $$;
create or replace function public.confirm_drive_organization_folder(p_integration_id uuid,p_file_id text) returns boolean language plpgsql security definer set search_path=public,pg_temp as $$ begin update public.reporting_drive_integrations set organization_drive_folder_id=coalesce(organization_drive_folder_id,p_file_id) where id=p_integration_id and (reserved_organization_drive_folder_id=p_file_id or organization_drive_folder_id=p_file_id); return found; end; $$;
create or replace function public.confirm_drive_event_folder(p_location_id uuid,p_file_id text) returns boolean language plpgsql security definer set search_path=public,pg_temp as $$ begin update public.event_drive_locations set event_drive_folder_id=coalesce(event_drive_folder_id,p_file_id) where id=p_location_id and (reserved_event_drive_folder_id=p_file_id or event_drive_folder_id=p_file_id); return found; end; $$;
create or replace function public.confirm_drive_reports_folder(p_location_id uuid,p_file_id text) returns boolean language plpgsql security definer set search_path=public,pg_temp as $$ begin update public.event_drive_locations set final_reports_folder_id=coalesce(final_reports_folder_id,p_file_id) where id=p_location_id and (reserved_final_reports_folder_id=p_file_id or final_reports_folder_id=p_file_id); return found; end; $$;
do $$ declare f text; begin foreach f in array array['reserve_drive_organization_folder_id(uuid,text)','reserve_drive_event_folder_id(uuid,text,bigint)','reserve_drive_reports_folder_id(uuid,text,bigint)','confirm_drive_organization_folder(uuid,text)','confirm_drive_event_folder(uuid,text)','confirm_drive_reports_folder(uuid,text)'] loop execute 'revoke all on function public.'||f||' from public,anon,authenticated'; execute 'grant execute on function public.'||f||' to service_role'; end loop; end $$;
