create or replace function public.create_physical_reservation_atomic(p_reservation jsonb,p_guests jsonb)
returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$
declare r reservations%rowtype; e events%rowtype; res resources%rowtype; elr event_layout_resources%rowtype; el event_layouts%rowtype; g jsonb; outg jsonb:='[]'; ord int; gid uuid; rid uuid; event_id uuid; resource_id uuid; vcount int;
begin
 if auth.uid() is null then raise exception 'reservation_unauthenticated' using errcode='28000'; end if;
 event_id:=(p_reservation->>'event_id')::uuid; resource_id:=(p_reservation->>'resource_id')::uuid; rid:=coalesce((p_reservation->>'id')::uuid,gen_random_uuid());
 select * into e from events where id=event_id and deleted_at is null for update; if not found then raise exception 'event_not_found' using errcode='P0002'; end if;
 if not exists(select 1 from profiles p join roles ro on ro.id=p.role_id and ro.deleted_at is null where p.user_id=current_app_user_id() and p.organization_id=e.organization_id and p.deleted_at is null and 'reservation.create'=any(ro.permissions)) then raise exception 'reservation_forbidden' using errcode='42501'; end if;
 if e.venue_id is null then raise exception 'event_venue_required' using errcode='22023'; end if;
 select x.* into el from event_layouts x where x.event_id=e.id and x.venue_id=e.venue_id and x.deleted_at is null and x.status='active'; if not found then raise exception 'event_layout_required' using errcode='22023'; end if;
 select * into res from resources where id=resource_id and deleted_at is null for update; if not found or res.venue_id<>e.venue_id then raise exception 'event_layout_resource_not_found' using errcode='P0002'; end if;
 select count(*) into vcount from event_layout_resources x where x.event_layout_id=el.id and x.deleted_at is null and x.status='active' and (x.source_resource_id=res.id or (x.source_resource_id is null and exists(select 1 from venue_layout_resources v where v.id=x.source_venue_layout_resource_id and v.source_resource_id=res.id))); if vcount<>1 then raise exception 'event_layout_resource_not_found' using errcode='P0002'; end if;
 select * into elr from event_layout_resources x where x.event_layout_id=el.id and x.deleted_at is null and x.status='active' and (x.source_resource_id=res.id or (x.source_resource_id is null and exists(select 1 from venue_layout_resources v where v.id=x.source_venue_layout_resource_id and v.source_resource_id=res.id))) limit 1;
 if (select count(*) from guests g where g.event_id=e.id and g.table_id=res.id::text and g.deleted_at is null and g.admission_status<>'Anulada' and g.reservation_status<>'Cancelled') + jsonb_array_length(p_guests) > greatest(res.capacity,0) then raise exception 'physical_capacity_exceeded' using errcode='22023'; end if;
 insert into reservations(id,code,name,event_id,event_name,date,time,table_name,table_id,table_capacity,holder_name,holder_document,holder_whatsapp,holder_email,reservation_type,payment_status,amount,advance,notes,guest_ids,status,timeline,event_layout_id,event_layout_resource_id,resource_id,commercial_snapshot,reference)
 values(rid,p_reservation->>'code',p_reservation->>'name',e.id,e.name,p_reservation->>'date',p_reservation->>'time',res.name,res.id::text,res.capacity,coalesce(p_reservation->>'holder_name',''),coalesce(p_reservation->>'holder_document',''),coalesce(p_reservation->>'holder_whatsapp',''),coalesce(p_reservation->>'holder_email',''),'Mesa',coalesce(p_reservation->>'payment_status','Pendiente'),coalesce(p_reservation->>'amount','0'),coalesce(p_reservation->>'advance','0'),coalesce(p_reservation->>'notes',''),array[]::text[],coalesce(p_reservation->>'status','Pending'),'[]'::jsonb,el.id,elr.id,res.id,(p_reservation->'commercial_snapshot'),p_reservation->>'reference');
 for g in select * from jsonb_array_elements(p_guests) loop
   gid:=coalesce((g->>'id')::uuid,gen_random_uuid()); select coalesce(max(access_ordinal),0)+1 into ord from guests where reservation_id=rid::text; insert into guests(id,event_id,guest_name,reservation_name,reservation_code,reservation_id,event_name,table_id,table_name,event_status,invitation_sequence,invitation_code,carnet,whatsapp,delivery_status,admission_status,reservation_status,qr_status,recent_change,no_whatsapp,no_invitation_sent,manual_admission,delivery_history,operator_activity,created_at,updated_at,access_ordinal) values(gid,e.id,g->>'guest_name',p_reservation->>'name',p_reservation->>'code',rid::text,e.name,res.id::text,res.name,'Próximo',coalesce(g->>'invitation_sequence',ord::text),format('%s-%s',p_reservation->>'code',lpad(ord::text,2,'0')),coalesce(g->>'carnet',''),coalesce(g->>'whatsapp',''),coalesce(g->>'delivery_status','Enviada'),coalesce(g->>'admission_status','Pendiente'),coalesce(p_reservation->>'status','Pending'),coalesce(g->>'qr_status','Válido'),true,false,false,false,'[]'::jsonb,'[]'::jsonb,now(),now(),ord); outg:=outg||jsonb_build_object('id',gid,'access_ordinal',ord,'invitation_code',format('%s-%s',p_reservation->>'code',lpad(ord::text,2,'0')),'table_id',res.id,'table_name',res.name); end loop;
 update reservations set guest_ids=array(select (x->>'id') from jsonb_array_elements(outg) x) where id=rid;
 return jsonb_build_object('reservation',to_jsonb((select x from reservations x where x.id=rid)),'guests',coalesce((select jsonb_agg(to_jsonb(x)) from guests x where x.reservation_id=rid::text and x.deleted_at is null),'[]'::jsonb));
end; $$;
alter function public.create_physical_reservation_atomic(jsonb,jsonb) owner to postgres;
revoke all on function public.create_physical_reservation_atomic(jsonb,jsonb) from public,anon,service_role;
grant execute on function public.create_physical_reservation_atomic(jsonb,jsonb) to authenticated;
